/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RandomImport } from './routes/random'
import { Route as FavoritesImport } from './routes/favorites'
import { Route as IndexImport } from './routes/index'
import { Route as SearchQueryImport } from './routes/search.$query'
import { Route as RecipeRecipeIdImport } from './routes/recipe.$recipeId'

// Create/Update Routes

const RandomRoute = RandomImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRoute = FavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchQueryRoute = SearchQueryImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRoute,
} as any)

const RecipeRecipeIdRoute = RecipeRecipeIdImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesImport
      parentRoute: typeof rootRoute
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomImport
      parentRoute: typeof rootRoute
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/random': typeof RandomRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/search/$query': typeof SearchQueryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/random': typeof RandomRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/search/$query': typeof SearchQueryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/random': typeof RandomRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/search/$query': typeof SearchQueryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/random'
    | '/recipe/$recipeId'
    | '/search/$query'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/random' | '/recipe/$recipeId' | '/search/$query'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/random'
    | '/recipe/$recipeId'
    | '/search/$query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  RandomRoute: typeof RandomRoute
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
  SearchQueryRoute: typeof SearchQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  RandomRoute: RandomRoute,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
  SearchQueryRoute: SearchQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favorites",
        "/random",
        "/recipe/$recipeId",
        "/search/$query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favorites": {
      "filePath": "favorites.tsx"
    },
    "/random": {
      "filePath": "random.tsx"
    },
    "/recipe/$recipeId": {
      "filePath": "recipe.$recipeId.tsx"
    },
    "/search/$query": {
      "filePath": "search.$query.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
